### ISSUE TITLE
Result window does not open when running specs

### ISSUE THREAD

**Issue by jedrekdomanski** [itmammoth/run-rspec.vim#20]
I have a bunch of tests in a spec file, when I run it I get this message:
![image](https://user-images.githubusercontent.com/5911945/36067344-43adbf6e-0ebb-11e8-97ef-4987dc22f169.png)
So I need to press Enter in order to open the result window.

Another thing is that I have 12 tests in my spec however it says "3 passed". It happens in every file, no matter how many tests I have in a spec. I order to see more result info, I need to come down to where it says "3 passed" with the cursor and press right arrow key
![image](https://user-images.githubusercontent.com/5911945/36067330-048d4656-0ebb-11e8-953e-8b58ea542b7b.png)
to see this:
![image](https://user-images.githubusercontent.com/5911945/36067370-de49bf82-0ebb-11e8-9b11-5850f0c962ef.png)

A little bit uncomfortable.

On the other hand, in a spec file with only 4 tests in it the result window opens right away. Is it an issue  with the number of tests in a spec file?

**Comment by itmammoth** [comment]
Hi @jedrekdomanski 
Let me know your rspec version.

**Comment by jedrekdomanski** [comment]
`rspec --version`
RSpec 3.7
  - rspec-core 3.7.1
  - rspec-expectations 3.7.0
  - rspec-mocks 3.7.0
  - rspec-rails 3.7.2
  - rspec-support 3.7.0

**Comment by itmammoth** [comment]
Hmm,, The rspec result that you attached looks like `skwp/vim-rspec`'s one.
Are you sure using my `itmammoth/run-rspec`?
These two plugins can not coexist because there are some conflicts between their commands.

**Comment by jedrekdomanski** [comment]
Hi,
I had skw/vim-rspec, that's true. After removing skw/vim-rspec the output
of `rspec --version` is the same, however now everything *works!*

*:)*

Thank you very much.

Jędrek

2018-02-12 2:58 GMT+01:00 ITMammoth <notifications@github.com>:

**Comment by itmammoth** [comment]
That's good to hear :D
